image: node:10.15.3
pipelines:
  branches:
    main:
      - step:
          name: Run Tests
          caches:
            - node
          script:
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
            - npm run test
      - step:
           name: Create artifact
           script: 
             - git archive --format=tar.gz main -o application.tar.gz 
           artifacts: 
           - application.tar.gz
      - step:
           name: Deploy to heroku
           deployment: production
           caches:
             - node
           script:
             - pipe: atlassian/heroku-deploy:1.1.4
               variables:
                 HEROKU_API_KEY: $HEROKU_API_KEY
                 HEROKU_APP_NAME: $HEROKU_APP_NAME
                 ZIP_FILE: "application.tar.gz"
                 WAIT: 'true'